# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34742e0d76c1815331d7e021d24b3b4c1a4c93ddd69e241dec444baf946c388606d755983d1323ccb331801e5722bf86c88c4ac5c7f0e8b0020e22a008b4efd9

test:
  secret_key_base: d82228053a571366b5eeb08f7993016f73698fc2c8d9cbe4af02f96ff4e5f61bfc99e7261507a010f91447cd5d9044c161b8ee41c78643975aec65363bfb54c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
